#!/bin/bash
# =============================================================================
# Platform — Platform Cluster Bootstrap
# =============================================================================
# Rootful Docker + k3d | Cilium CNI | Istio Ambient | Prometheus | ArgoCD
# =============================================================================
set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'
YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ OK ]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()   { echo -e "${RED}[ERR ]${NC}  $*"; exit 1; }
banner(){ echo -e "\n${BOLD}── $* ────────────────────────────────────────────────${NC}"; }

# =============================================================================
# CONFIG — edit these to match your environment
# =============================================================================
CLUSTER_NAME="platform"

# ── Network layout ────────────────────────────────────────────────────────────
# Choose a /24 that does NOT overlap with:
#   • your LAN  (e.g. 192.168.1.0/24)
#   • your VPN  (commonly 10.x.x.x or 172.16-31.x.x)
#   • other Docker networks (docker network ls --format '{{.Name}}' | xargs docker network inspect | grep Subnet)
DOCKER_NETWORK_NAME="platform-net"
DOCKER_SUBNET="172.100.0.0/24"       # k3d node IPs (host bridge)
DOCKER_GATEWAY="172.100.0.1"

# k3s cluster CIDRs — must NOT overlap with Docker subnet above
POD_CIDR="10.42.0.0/16"             # Cilium pod addresses
SERVICE_CIDR="10.43.0.0/16"         # Kubernetes service VIPs
CLUSTER_DNS="10.43.0.10"            # CoreDNS ClusterIP

# ── Ports exposed on the host loopback ───────────────────────────────────────
# Use 18080/18443 so these don't conflict with the Podman ingress (8080/8443).
# The Podman ingress proxies *.internal traffic to these ports via
# host.containers.internal (169.254.1.2 → 127.0.0.1 on the host).
HOST_HTTP_PORT="18080"
HOST_HTTPS_PORT="18443"

# ── Kubernetes API server ─────────────────────────────────────────────────────
# Exposed on 0.0.0.0:6443 (nftables restricts to k3s-vpn sources).
# Users connect via kubernetes.internal:6443 (DNS resolves to k3s-vpn IP).
K8S_API_PORT="6443"
K8S_EXTERNAL_HOST="kubernetes.internal"   # kubeconfig server address for users
K8S_VPN_IP="10.10.10.200"                 # k3s-vpn interface IP on this host

# ── Internal DNS names (add to /etc/hosts or local DNS) ──────────────────────
DOMAINS=("grafana.internal" "prometheus.internal" "argocd.internal")

# ── Certificate validity ──────────────────────────────────────────────────────
CERT_DIR="certs"
CERT_DAYS=825    # ≤2 yr leaf (browser requirement)

# ── Intermediate CA — provided externally, never generated by this script ─────
# Place your intermediate CA files here before running:
#   certs/ca.crt   — intermediate CA certificate (PEM, may include chain up to root)
#   certs/ca.key   — intermediate CA private key  (PEM, keep secret)
CA_CERT="${CERT_DIR}/ca.crt"
CA_KEY="${CERT_DIR}/ca.key"

# ── Helm chart versions (pin for reproducibility) ────────────────────────────
CILIUM_VERSION="1.18.4"
PROMETHEUS_STACK_VERSION="77.11.1"
ARGOCD_VERSION="7.10.3"

# =============================================================================
# 1 — Required utilities
# =============================================================================
banner "1 — Checking required utilities"
# istioctl may be installed to ~/.istioctl/bin rather than system PATH
export PATH="${HOME}/.istioctl/bin:${PATH}"

for cmd in k3d helm kubectl istioctl openssl docker; do
    command -v "$cmd" >/dev/null 2>&1 || die "$cmd not found. Install it and re-run."
done
ok "All required utilities present."

# Docker must be running as the current user (rootful socket)
docker info >/dev/null 2>&1 || die "Docker daemon unreachable. Is dockerd running and the current user in the 'docker' group?"

# =============================================================================
# 2 — Firewall pre-flight
# =============================================================================
banner "2 — Firewall pre-flight"

# Warn about UFW — it can silently drop Docker forwarded traffic
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
    warn "UFW is active. Docker FORWARD rules may be blocked."
    warn "Run the following once to allow k3d cluster traffic:"
    warn "  sudo ufw allow in on br-${DOCKER_NETWORK_NAME} || true"
    warn "  sudo ufw allow out on br-${DOCKER_NETWORK_NAME} || true"
    warn "  # Also ensure /etc/ufw/after.rules has DOCKER-USER ACCEPT rules."
    echo ""
    read -r -p "Continue anyway? [y/N] " _confirm
    [[ "${_confirm,,}" == "y" ]] || exit 0
fi

# Ensure iptables FORWARD is permissive for the k3d bridge network.
# Docker injects rules into DOCKER and DOCKER-USER chains, but on some distros
# the default FORWARD policy is DROP, which blocks inter-node pod traffic.
if command -v iptables >/dev/null 2>&1; then
    if sudo iptables -C FORWARD -j ACCEPT 2>/dev/null; then
        ok "FORWARD chain already accepts."
    else
        warn "Adding permissive FORWARD rule (required for CNI traffic between k3d nodes)."
        warn "This affects the session only. Make it permanent via iptables-persistent / nftables."
        sudo iptables -I FORWARD 1 -j ACCEPT || warn "Could not set FORWARD rule (non-fatal if Docker is managing it)."
    fi
fi

ok "Firewall pre-flight complete."

# =============================================================================
# 3 — Helm repos
# =============================================================================
banner "3 — Helm repos"
helm repo add cilium              https://helm.cilium.io                                   || true
helm repo add istio               https://istio-release.storage.googleapis.com/charts      || true
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts      || true
helm repo add argo                https://argoproj.github.io/argo-helm                     || true
helm repo update
ok "Helm repos updated."

# =============================================================================
# 4 — Docker network
# =============================================================================
banner "4 — Docker network"

# Remove stale network that might hold onto old subnet allocations
if docker network inspect "$DOCKER_NETWORK_NAME" >/dev/null 2>&1; then
    warn "Removing existing Docker network '$DOCKER_NETWORK_NAME'..."
    # k3d cluster delete will remove containers; remove network after
    k3d cluster delete "$CLUSTER_NAME" 2>/dev/null || true
    docker network rm "$DOCKER_NETWORK_NAME" 2>/dev/null || true
else
    k3d cluster delete "$CLUSTER_NAME" 2>/dev/null || true
fi

docker network create \
    --driver bridge \
    --subnet  "$DOCKER_SUBNET" \
    --gateway "$DOCKER_GATEWAY" \
    --opt "com.docker.network.bridge.name=br-${DOCKER_NETWORK_NAME}" \
    "$DOCKER_NETWORK_NAME"

ok "Docker network '$DOCKER_NETWORK_NAME' created (${DOCKER_SUBNET})."

# =============================================================================
# 5 — Create HA K3d cluster
# =============================================================================
banner "5 — Create K3d cluster"
info "Creating '$CLUSTER_NAME': 3 control-plane + 3 worker nodes…"

k3d cluster create "$CLUSTER_NAME" \
    --network "$DOCKER_NETWORK_NAME" \
    --k3s-arg "--flannel-backend=none@server:*" \
    --k3s-arg "--disable-network-policy@server:*" \
    --k3s-arg "--disable=traefik@server:*" \
    --k3s-arg "--cluster-cidr=${POD_CIDR}@server:*" \
    --k3s-arg "--service-cidr=${SERVICE_CIDR}@server:*" \
    --k3s-arg "--cluster-dns=${CLUSTER_DNS}@server:*" \
    --k3s-arg "--tls-san=${K8S_VPN_IP}@server:*" \
    --k3s-arg "--tls-san=${K8S_EXTERNAL_HOST}@server:*" \
    --registry-create registry.localhost:5000 \
    -p "127.0.0.1:${HOST_HTTP_PORT}:80@loadbalancer" \
    -p "127.0.0.1:${HOST_HTTPS_PORT}:443@loadbalancer" \
    -p "0.0.0.0:${K8S_API_PORT}:6443@loadbalancer" \
    --servers 3 \
    --agents  3 \
    --timeout 180s

info "Waiting for nodes to be Ready…"
kubectl wait --for=condition=Ready nodes --all --timeout=180s
ok "Cluster created. $(kubectl get nodes --no-headers | wc -l) nodes Ready."

# =============================================================================
# 6 — Install Cilium
# =============================================================================
banner "6 — Cilium CNI"
info "Installing Cilium ${CILIUM_VERSION}…"

helm install cilium cilium/cilium \
    --namespace kube-system \
    --version  "$CILIUM_VERSION" \
    --values   values/cilium/initial.yaml \
    --set      "ipam.operator.clusterPoolIPv4PodCIDRList=${POD_CIDR}" \
    --wait --timeout 5m

info "Waiting for Cilium agent pods…"
kubectl -n kube-system wait \
    --for=condition=Ready pod \
    -l app.kubernetes.io/name=cilium-agent \
    --timeout=180s

ok "Cilium installed."

# =============================================================================
# 7 — Install Istio Ambient
# =============================================================================
banner "7 — Istio Ambient"
info "Installing Istio Ambient mesh…"
istioctl install --set profile=ambient --skip-confirmation --verify
ok "Istio Ambient installed."

# =============================================================================
# 8 — Platform namespaces
# =============================================================================
banner "8 — Platform namespaces"

declare -A NS_LABELS=(
    ["monitoring"]="istio.io/dataplane-mode=ambient"
    ["argocd"]="istio.io/dataplane-mode=ambient"
    ["platform-system"]=""
)

for ns in "${!NS_LABELS[@]}"; do
    kubectl create namespace "$ns" --dry-run=client -o yaml | kubectl apply -f -
    if [[ -n "${NS_LABELS[$ns]}" ]]; then
        kubectl label namespace "$ns" ${NS_LABELS[$ns]} --overwrite
    fi
done

ok "Namespaces created."

# =============================================================================
# 9 — TLS certificates (local CA → all internal domains)
# =============================================================================
banner "9 — TLS certificates"
mkdir -p "$CERT_DIR"

# Verify the intermediate CA is in place
[[ -f "$CA_CERT" ]] || die "Intermediate CA certificate not found at ${CA_CERT}. Place your CA cert there before running."
[[ -f "$CA_KEY"  ]] || die "Intermediate CA private key not found at ${CA_KEY}. Place your CA key there before running."

# Validate the CA cert/key pair match
CA_CERT_MOD=$(openssl x509 -noout -modulus -in "$CA_CERT" 2>/dev/null | md5sum)
CA_KEY_MOD=$(openssl rsa  -noout -modulus -in "$CA_KEY"  2>/dev/null | md5sum)
[[ "$CA_CERT_MOD" == "$CA_KEY_MOD" ]] || die "CA certificate and key do not match. Check ${CA_CERT} and ${CA_KEY}."

ok "Intermediate CA verified: $(openssl x509 -noout -subject -in "$CA_CERT" | sed 's/subject=//')"

generate_cert() {
    local domain="$1"
    openssl genrsa -out "${CERT_DIR}/${domain}.key" 2048 2>/dev/null
    openssl req -new \
        -key "${CERT_DIR}/${domain}.key" \
        -out "${CERT_DIR}/${domain}.csr" \
        -subj "/CN=${domain}/O=Platform" 2>/dev/null
    openssl x509 -req \
        -in  "${CERT_DIR}/${domain}.csr" \
        -CA  "$CA_CERT" -CAkey "$CA_KEY" \
        -CAcreateserial \
        -out "${CERT_DIR}/${domain}.crt" \
        -days "$CERT_DAYS" -sha256 \
        -extfile <(printf "subjectAltName=DNS:%s\nbasicConstraints=CA:FALSE\nextendedKeyUsage=serverAuth\n" "$domain") \
        2>/dev/null
    # Build fullchain: leaf cert + intermediate CA cert.
    # Istio gateway presents this chain so clients can verify up to the root.
    cat "${CERT_DIR}/${domain}.crt" "$CA_CERT" > "${CERT_DIR}/${domain}.fullchain.crt"
    ok "Certificate: ${domain}"
}

for domain in "${DOMAINS[@]}"; do
    generate_cert "$domain"
done

# =============================================================================
# 10 — TLS secrets (must live in istio-system — where the gateway pod runs)
# =============================================================================
banner "10 — TLS secrets in istio-system"

for domain in "${DOMAINS[@]}"; do
    secret_name="${domain%%.*}-tls"   # grafana-tls, prometheus-tls, argocd-tls
    kubectl create secret tls "$secret_name" \
        --namespace istio-system \
        --cert="${CERT_DIR}/${domain}.fullchain.crt" \
        --key="${CERT_DIR}/${domain}.key" \
        --dry-run=client -o yaml | kubectl apply -f -
done

ok "TLS secrets created in istio-system."

# =============================================================================
# 11 — Grafana credentials
# =============================================================================
banner "11 — Grafana credentials"
GRAFANA_PASSWORD=$(openssl rand -base64 24)

kubectl create secret generic grafana-credentials \
    --namespace monitoring \
    --from-literal=admin-user=admin \
    --from-literal=password="${GRAFANA_PASSWORD}" \
    --dry-run=client -o yaml | kubectl apply -f -

ok "Grafana secret created."

# =============================================================================
# 12 — Prometheus + Grafana stack
# =============================================================================
banner "12 — kube-prometheus-stack"
info "Installing kube-prometheus-stack ${PROMETHEUS_STACK_VERSION}…"

helm install monitoring prometheus-community/kube-prometheus-stack \
    --namespace monitoring \
    --version   "$PROMETHEUS_STACK_VERSION" \
    --values    values/prometheus/initial.yaml \
    --wait --timeout 10m

ok "Prometheus/Grafana stack installed."

# =============================================================================
# 13 — ArgoCD
# =============================================================================
banner "13 — ArgoCD"
info "Installing ArgoCD ${ARGOCD_VERSION}…"

helm install argocd argo/argo-cd \
    --namespace argocd \
    --version   "$ARGOCD_VERSION" \
    --values    values/argocd/initial.yaml \
    --wait --timeout 10m

ARGOCD_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret \
    -o jsonpath="{.data.password}" | base64 -d)

ok "ArgoCD installed."

# =============================================================================
# 14 — Cilium Prometheus metrics (post-CRD upgrade)
# =============================================================================
banner "14 — Cilium ServiceMonitor"
info "Upgrading Cilium with Prometheus integration…"

helm upgrade cilium cilium/cilium \
    --namespace kube-system \
    --version   "$CILIUM_VERSION" \
    --reuse-values \
    --values    values/cilium/post-prometheus-crds.yaml \
    --wait --timeout 5m

ok "Cilium metrics configured."

# =============================================================================
# 15 — Platform Gateway + VirtualServices
# =============================================================================
banner "15 — Platform ingress gateway"

kubectl apply -f - <<'EOF'
# ── Platform Gateway ─────────────────────────────────────────────────────────
# Port 80  — HTTP traffic from the Podman nginx ingress (TLS already terminated
#             at the ingress layer; Podman proxies to host.containers.internal:18080)
# Port 443 — HTTPS for direct in-cluster access and future use cases.
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    # HTTP — receives traffic from Podman ingress (TLS terminated upstream)
    - port: {number: 80, name: http, protocol: HTTP}
      hosts: ["grafana.internal", "prometheus.internal", "argocd.internal"]
    # HTTPS — TLS terminated at Istio (direct cluster access)
    - port: {number: 443, name: https-grafana, protocol: HTTPS}
      tls:  {mode: SIMPLE, credentialName: grafana-tls}
      hosts: ["grafana.internal"]
    - port: {number: 443, name: https-prometheus, protocol: HTTPS}
      tls:  {mode: SIMPLE, credentialName: prometheus-tls}
      hosts: ["prometheus.internal"]
    - port: {number: 443, name: https-argocd, protocol: HTTPS}
      tls:  {mode: SIMPLE, credentialName: argocd-tls}
      hosts: ["argocd.internal"]
---
# ── Grafana VirtualService ───────────────────────────────────────────────────
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: monitoring
spec:
  hosts: ["grafana.internal"]
  gateways: ["istio-system/platform-gateway"]
  http:
    - route:
        - destination:
            host: monitoring-grafana.monitoring.svc.cluster.local
            port: {number: 3000}
---
# ── Prometheus VirtualService ────────────────────────────────────────────────
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus
  namespace: monitoring
spec:
  hosts: ["prometheus.internal"]
  gateways: ["istio-system/platform-gateway"]
  http:
    - route:
        - destination:
            host: monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local
            port: {number: 9090}
---
# ── ArgoCD VirtualService ────────────────────────────────────────────────────
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
spec:
  hosts: ["argocd.internal"]
  gateways: ["istio-system/platform-gateway"]
  http:
    - route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port: {number: 80}
EOF

ok "Platform gateway and virtual services applied."

# =============================================================================
# 16 — Base RBAC
# =============================================================================
banner "16 — Platform RBAC"
kubectl apply -f rbac/cluster-roles.yaml
ok "RBAC ClusterRoles applied."

# =============================================================================
# 17 — Patch kubeconfig server address
# =============================================================================
banner "17 — Kubeconfig"
# k3d sets the server to https://0.0.0.0:6443 which only works locally.
# Replace with the VPN hostname so distributed kubeconfigs work for VPN users.
KUBECONFIG_PATH="${HOME}/.kube/config"
if [[ -f "$KUBECONFIG_PATH" ]]; then
    sed -i "s|https://0.0.0.0:${K8S_API_PORT}|https://${K8S_EXTERNAL_HOST}:${K8S_API_PORT}|g" "$KUBECONFIG_PATH"
    ok "Kubeconfig server patched to https://${K8S_EXTERNAL_HOST}:${K8S_API_PORT}"
fi

# =============================================================================
# Done
# =============================================================================
echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║  Platform cluster is ready                                 ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Access (via k3s-vpn — 10.10.10.0/24)${NC}"
echo -e "  ┌─────────────────────────────────────────────────────────────┐"
echo -e "  │  Grafana     https://grafana.internal                       │"
echo -e "  │              admin / ${GRAFANA_PASSWORD}                     │"
echo -e "  │                                                             │"
echo -e "  │  Prometheus  https://prometheus.internal                    │"
echo -e "  │                                                             │"
echo -e "  │  ArgoCD      https://argocd.internal                       │"
echo -e "  │              admin / ${ARGOCD_PASSWORD}                     │"
echo -e "  └─────────────────────────────────────────────────────────────┘"
echo ""
echo -e "  ${BOLD}Kubernetes API${NC}  https://${K8S_EXTERNAL_HOST}:${K8S_API_PORT}"
echo -e "  ${BOLD}Registry${NC}        registry.localhost:5000"
echo ""
echo -e "  ${BOLD}Network layout${NC}"
echo -e "  ├── Docker bridge  ${DOCKER_SUBNET}  (k3d node IPs)"
echo -e "  ├── Pod CIDR       ${POD_CIDR}      (Cilium / workloads)"
echo -e "  └── Service CIDR   ${SERVICE_CIDR}      (Kubernetes services)"
echo ""
echo -e "  ${BOLD}VPN client /etc/hosts${NC} (add on each client machine)"
echo -e "  ${K8S_VPN_IP}  grafana.internal prometheus.internal argocd.internal"
echo -e "  ${K8S_VPN_IP}  platform.internal ${K8S_EXTERNAL_HOST}"
echo ""
echo -e "  ${BOLD}User provisioning${NC}"
echo -e "  ./create-user.sh <username> <role>"
echo -e "  Roles: platform-admin | developer | viewer"
echo ""
echo -e "  ${BOLD}Ingress note${NC}"
echo -e "  Deploy wildcard TLS cert to /etc/ssl/certs/wildcard.internal.fullchain.crt"
echo -e "  and private key to /etc/ssl/private/wildcard.internal.key"
echo -e "  then start your reverse proxy (e.g. nginx, Caddy, or Podman ingress)"
echo ""
