apiVersion: v2
name: picoservice-rs
description: A Helm chart for a picoservice written in Rust/Axum

type: application

version: 0.1.0

appVersion: "0.1.0"

maintainers:
  - name: Robert Shalders
keywords:
  - rust
  - axum
  - metrics
  - logging
  - tracing